name: cf-networking
version: 0.6.0
description: Helm chart for CF Networking components
type: application
apiVersion: v2
# renovate: depName=cf-networking-release image=ghcr.io/cloudfoundry/k8s/policy-server
appVersion: 3.98.0
