name: cf-networking
version: 0.8.0
description: Helm chart for CF Networking components
type: application
apiVersion: v2
# renovate: image=ghcr.io/cloudfoundry/k8s/policy-server depName=cf-networking-release
appVersion: 3.98.0
