{{ if .Values.cloudController.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cc-uploader
  labels:
    app: cc-uploader
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cc-uploader-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-uploader
  template:
    metadata:
      labels:
        app: cc-uploader
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cc-uploader-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: cc-uploader
          image: {{ .Values.ccUploader.image.repository }}:{{ default .Chart.AppVersion .Values.ccUploader.image.tag }}
          imagePullPolicy: {{ .Values.ccUploader.image.imagePullPolicy }}
          ports:
            - containerPort: 9090
          {{- if .Values.ccUploader.resources }}
          resources:
            {{- toYaml .Values.ccUploader.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cc-uploader
              mountPath: /etc/ssl/certs/cc-uploader
            - name: cc-uploader-config
              mountPath: /cc-uploader
      {{- if .Values.ccUploader.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.ccUploader.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.ccUploader.tolerations }}
      tolerations:
        {{- toYaml .Values.ccUploader.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: cc-uploader
          secret:
            secretName: {{ default "cc-uploader" .Values.ccUploader.certificateSecret }}
        - name: cc-uploader-config
          configMap:
            name: cc-uploader-configmap
---
kind: Service
apiVersion: v1
metadata:
  name: cc-uploader
  labels:
    app: cc-uploader
spec:
  ports:
    - port: 9090
      targetPort: 9090
      name: tcp
      protocol: TCP
  selector:
    app: cc-uploader
---
{{ if not .Values.ccUploader.certificateSecret }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cc-uploader
spec:
  secretName: cc-uploader
  commonName: client
  dnsNames:
    - localhost
    - cc-uploader
    - cc-uploader.{{ .Release.Namespace }}.svc
    - cc-uploader.{{ .Release.Namespace }}.svc.cluster.local
    - "{{ .Values.ccUploader.hostname }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
{{end }}
{{ end }}