{{- if .Values.policyServer.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-server-route-registrar-configmap
data:
  route-registrar.json: |-
    {
      "message_bus_servers": [
        {
          "host": "nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
        }
      ],
      "nats_mtls_config": {
        "enabled": true,
        "cert_path": "/etc/ssl/certs/policy-server/tls.crt",
        "key_path": "/etc/ssl/certs/policy-server/tls.key",
        "ca_path": "/etc/ssl/certs/policy-server/ca.crt"
      },
      "host": "",
      "routes": [
        {
          "name": "policy-server",
          "port": 4002,
          "registration_interval": "10s",
          "server_cert_domain_san": "{{ .Values.policyServer.externalDomain }}",
          "uris": [
            "{{ .Values.policyServer.externalDomain }}/networking"
          ]
        }
      ]
    }
{{- end }}