{{- if .Values.policyServer.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: policy-server
  labels:
    app: policy-server
  annotations:
    checksum/config: {{ cat (include (print $.Template.BasePath "/policy-server-configmap.yaml") .) (include (print $.Template.BasePath "/policy-server-route-registrar-configmap.yaml") .) | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-server
  template:
    metadata:
      labels:
        app: policy-server
      annotations:
        checksum/config: {{ cat (include (print $.Template.BasePath "/policy-server-configmap.yaml") .) (include (print $.Template.BasePath "/policy-server-route-registrar-configmap.yaml") .) | sha256sum }}
    spec:
      containers:
        - name: policy-server
          image: {{ .Values.policyServer.image.repository }}:{{ default .Chart.AppVersion .Values.policyServer.image.tag }}
          imagePullPolicy: {{ .Values.policyServer.image.imagePullPolicy }}
          command: [ "/usr/local/bin/policy-server" ]
          args:
          - -config-file
          - /policy-server/policy-server.json
          volumeMounts:
            - name: policy-server-config
              mountPath: /policy-server
            - name: policy-server
              mountPath: /etc/ssl/certs/policy-server
              readOnly: true
          {{- if .Values.policyServer.resources }}
          resources:
            {{- toYaml .Values.policyServer.resources | nindent 12 }}
          {{- end }}
        - name: policy-server-internal
          image: {{ .Values.policyServer.image.repository }}:{{ default .Chart.AppVersion .Values.policyServer.image.tag }}
          imagePullPolicy: {{ .Values.policyServer.image.imagePullPolicy }}
          command: [ "/usr/local/bin/policy-server-internal" ]
          args:
          - -config-file
          - /policy-server/policy-server-internal.json
          volumeMounts:
            - name: policy-server-config
              mountPath: /policy-server
            - name: policy-server
              mountPath: /etc/ssl/certs/policy-server
              readOnly: true
          {{- if .Values.policyServer.resources }}
          resources:
            {{- toYaml .Values.policyServer.resources | nindent 12 }}
          {{- end }}
        - name: asg-syncer
          image: {{ .Values.policyServer.image.repository }}:{{ default .Chart.AppVersion .Values.policyServer.image.tag }}
          imagePullPolicy: {{ .Values.policyServer.image.imagePullPolicy }}
          command: [ "/usr/local/bin/policy-server-asg-syncer" ]
          args:
          - -config-file
          - /policy-server/policy-server-asg-syncer.json
          volumeMounts:
            - name: policy-server-config
              mountPath: /policy-server
            - name: policy-server
              mountPath: /etc/ssl/certs/policy-server
              readOnly: true
          {{- if .Values.policyServer.resources }}
          resources:
            {{- toYaml .Values.policyServer.resources | nindent 12 }}
          {{- end }}
        - name: route-registrar
          image: {{ .Values.routeRegistrar.image.repository }}:{{ .Values.routeRegistrar.image.tag }}
          imagePullPolicy: {{ .Values.routeRegistrar.image.imagePullPolicy }}
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- if .Values.routeRegistrar.resources }}
          resources:
            {{- toYaml .Values.routeRegistrar.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: policy-server
              mountPath: /etc/ssl/certs/policy-server
            - name: etc-route-registrar
              mountPath: /etc/route-registrar-template
            - name: tmpdir
              mountPath: /tmp
      {{- if .Values.policyServer.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.policyServer.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.policyServer.tolerations }}
      tolerations:
        {{- toYaml .Values.policyServer.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: policy-server-config
          configMap:
            name: policy-server-configmap
        - name: policy-server
          secret:
            secretName: {{ default "policy-server" .Values.policyServer.certificateSecret }}
        - name: etc-route-registrar
          configMap:
            name: policy-server-route-registrar-configmap
        - name: tmpdir
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: policy-server
  labels:
    app: policy-server
spec:
  ports:
  - port: 4003
    name: https
    targetPort: 4003
    appProtocol: kubernetes.io/h2c
  selector:
    app: policy-server
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: policy-server
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: policy-server
  rules:
    - backendRefs:
        - name: policy-server
          port: 4003
---
{{- if not .Values.policyServer.certificateSecret }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: policy-server
spec:
  secretName: policy-server
  commonName: client
  dnsNames:
    - policy-server
    - policy-server.{{ .Release.Namespace }}.svc
    - policy-server.{{ .Release.Namespace }}.svc.cluster.local
    - "{{ .Values.policyServer.hostname }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
{{- end }}
{{- end }}
