name: credhub
version: 0.8.0
description: Helm chart for CredHub components
type: application
apiVersion: v2
# renovate: image=europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/public/cf/credhub depName=credhub-release
appVersion: 2.14.17
