{{- if .Values.auctioneer.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: auctioneer
  labels:
    app: auctioneer
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/auctioneer-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auctioneer
  template:
    metadata:
      labels:
        app: auctioneer
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/auctioneer-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: auctioneer
          image: {{ .Values.auctioneer.image.repository }}:{{ default .Chart.AppVersion .Values.auctioneer.image.tag }}
          imagePullPolicy: {{ .Values.auctioneer.image.imagePullPolicy }}
          ports:
            - containerPort: 8889
          {{- if .Values.auctioneer.resources }}
          resources:
            {{- toYaml .Values.auctioneer.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: auctioneer
              mountPath: /etc/ssl/certs/auctioneer
            - name: auctioneer-config
              mountPath: /auctioneer
      {{- if .Values.auctioneer.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.auctioneer.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.auctioneer.tolerations }}
      tolerations:
        {{- toYaml .Values.auctioneer.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: auctioneer
          secret:
            secretName: {{ default "auctioneer" .Values.auctioneer.certificateSecret }}
        - name: auctioneer-config
          configMap:
            name: auctioneer-configmap
---
kind: Service
apiVersion: v1
metadata:
  name: auctioneer
  labels:
    app: auctioneer
spec:
  ports:
    - port: 9016
      targetPort: 9016
      protocol: TCP
  selector:
    app: auctioneer
---
{{ if not .Values.auctioneer.certificateSecret }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auctioneer
spec:
  secretName: auctioneer
  commonName: auctioneer
  dnsNames:
    - auctioneer
    - auctioneer.{{ .Release.Namespace }}.svc
    - auctioneer.{{ .Release.Namespace }}.svc.cluster.local
    - "{{ .Values.auctioneer.hostname }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
{{end }}
{{- end }}