{{- if .Values.locket.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: locket
  labels:
    app: locket
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/locket-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locket
  template:
    metadata:
      labels:
        app: locket
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/locket-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: locket
          image: {{ .Values.locket.image.repository }}:{{ default .Chart.AppVersion .Values.locket.image.tag }}
          imagePullPolicy: {{ .Values.locket.image.imagePullPolicy }}
          ports:
            - containerPort: 8891
          {{- if .Values.locket.resources }}
          resources:
            {{- toYaml .Values.locket.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: locket
              mountPath: /etc/ssl/certs/locket
            - name: postgres-tls
              mountPath: /etc/ssl/certs/postgres
            - name: locket-config
              mountPath: /locket
      {{- if .Values.locket.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.locket.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.locket.tolerations }}
      tolerations:
        {{- toYaml .Values.locket.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: locket
          secret:
            secretName: {{ default "locket" .Values.locket.certificateSecret }}
        - name: postgres-tls
          secret:
            secretName: postgres-tls
        - name: locket-config
          configMap:
            name: locket-configmap
---
kind: Service
apiVersion: v1
metadata:
  name: locket
  labels:
    app: locket
spec:
  ports:
    - port: 8891
      targetPort: 8891
      protocol: TCP
  selector:
    app: locket
---
{{ if not .Values.locket.certificateSecret }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: locket
spec:
  secretName: locket
  commonName: client
  dnsNames:
    - locket
    - locket.{{ .Release.Namespace }}.svc
    - locket.{{ .Release.Namespace }}.svc.cluster.local
    - "{{ .Values.locket.hostname }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
{{end }}
{{- end }}