name: log-cache
version: 0.7.0
description: Helm chart for Log Cache components
type: application
apiVersion: v2
# renovate: image=ghcr.io/cloudfoundry/k8s/gateway depName=log-cache-release
appVersion: 3.2.4
