name: loggregator-agent
version: 0.8.0
description: Helm chart for Loggregator Agent components
type: application
apiVersion: v2
# renovate: image=ghcr.io/cloudfoundry/k8s/syslog-binding-cache depName=loggregator-agent-release
appVersion: 8.3.13
