name: routing
version: 0.11.0
description: Helm chart for Gorouter components
type: application
apiVersion: v2
# renovate: image=ghcr.io/cloudfoundry/k8s/gorouter depName=routing-release
appVersion: 0.362.0
