name: nfs-volume-release
apiVersion: v2
version: 0.3.0
description: A Helm chart for deploying NFS Volume Release components
# renovate: image=ghcr.io/cloudfoundry/k8s/nfsbroker depName=nfs-volume-release
appVersion: 7.47.0
